spring:
  datasource:
    url: jdbc:mysql://39.105.123.124:3306//springbootdemo
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      #      更新或者创建数据表结构
      ddl-auto: update
    #      控制台显示sql
    show-sql: true
  thymeleaf:
    cache: false
  mvc:
    date-format: yyyy-MM-dd
server:
  context-path: /demo
  port: 80


